services:
  - type: web
    name: pdf-extractor-server
    runtime: docker
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false 